spring:
  config:
    import:
      - optional:file:.env[.properties]
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    format_sql: true
    use_sql_comments: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
  application:
    name: wadada

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  #      port: ${ REDIS_PORT }
  jwt:
    header: Authorization
    secret: ${JWT_KEY}
    access-token-validity-in-seconds: ${JWT_ACCESS_VALIDITY_SECONDS}
    refresh-token-validity-in-seconds: ${JWT_REFRESH_VALIDITY_SECONDS}

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: e1f258c84a001ab789ff5de179f253a1


  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}

    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
aes:
  secret-key: ${AES_KEY}

cloud:
  aws:
    credentials:
      access-key: AKIAUK2ZEHMYOWLQWCFJ
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: andyimagebucket

#cloud:
#  aws:
#    s3:
#      bucket: ${ S3_BUCKET }
#    credentials:
#      access-key: ${ S3_ACCESS }
#      secret-key: ${ S3_SECRET }
#    region:
#      static: ap-northeast-2
#      auto: false
#    stack:
#      auto: false

server:
  port: 8080








# RabbitMQ queue, exchange, routing-key ??
#rabbitmq:
#  queue.name: test01queue
#  exchange.name: test01
#  routing.eky: ${RABBITMQ_ROUTING
rabbitmq:
  queue.name: marathon1
  exchange.name: test01
  routing.key: ${RABBITMQ_ROUTING_KEY}

  marathon.name: marathon
  marathon1.name: marathon1
  marathon2.name: marathon2
  marathon3.name: marathon3
#  marathon.queue.name : marathon
#  marathon.exchange.name : marathon
#  marathon.routing.key : marathon
